
CREATE TABLE [dbo].[ENCABEZADOS_RECEPCION] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [CVE_DOC]     VARCHAR (50)  NULL,
    [DOC_ANT]     VARCHAR (50)  NULL,
    [CVE_CLPV]    VARCHAR (50)  NULL,
    [FECHA_APLI]  DATETIME      NULL,
    [CAN_TOT]     FLOAT (53)    NULL,
    [RFC]         VARCHAR (50)  NULL,
    [NOMBRE]      VARCHAR (255) NULL,
    [CALLE]       VARCHAR (120) NULL,
    [COLONIA]     VARCHAR (50)  NULL,
    [ESTADO]      VARCHAR (50)  NULL,
    [CODIGO]      VARCHAR (50)  NULL,
    [TELEFONO]    VARCHAR (50)  NULL,
    [STR_OBS]     VARCHAR (255) NULL,
    [NUMEXT]      VARCHAR (255) NULL,
    [LOCALIDAD]   VARCHAR (255) NULL,
    [MUNICIPIO]   VARCHAR (255) NULL,
    [TOTAL_LETRA] VARCHAR (255) NULL,
    CONSTRAINT [PK_ENCABEZADOS_RECEPCION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


CREATE TABLE [dbo].[PARTIDAS_RECEPCION] (
    [ID]          INT          IDENTITY (1, 1) NOT NULL,
    [DOC_ANT]     VARCHAR (50) NULL,
    [CVE_DOC]     VARCHAR (50) NULL,
    [FECHA_ENT]   DATETIME     NULL,
    [E_LTPD]      INT          NULL,
    [CVE_ART]     VARCHAR (50) NULL,
    [CANT]        FLOAT (53)   NULL,
    [UNI_VENTA]   VARCHAR (50) NULL,
    [DESCR]       VARCHAR (50) NULL,
    [CTRL_ALM]    VARCHAR (50) NULL,
    [LOTE]        VARCHAR (50) NULL,
    [PREC]        FLOAT (53)   NULL,
    [TOT_PARTIDA] FLOAT (53)   NULL,
    CONSTRAINT [PK_PARTIDAS_RECEPCION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

);

CREATE TABLE [dbo].[IMG] (
    [ID]       INT           IDENTITY (1, 1) NOT NULL,
    [RUTA_IMG] VARCHAR (250) NULL,
    CONSTRAINT [PK_IMG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

